# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "innovative-transaction-app"
client_id = "97cfd01dd216d17197656ceb63674093"
application_url = "https://fever-calm-pushed-strain.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://fever-calm-pushed-strain.trycloudflare.com/auth/callback",
  "https://fever-calm-pushed-strain.trycloudflare.com/auth/shopify/callback",
  "https://fever-calm-pushed-strain.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "teststore597.myshopify.com"
